version: '3.8'
services:
  db:
    image: test_image:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD=postgres
      POSTGRES_USER=postgres
      POSTGRES_DB=testdb
    volumes:
      - ../init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
  